// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Ibh5HQeKO7O1TbuP4yQWDRyxeWsy80k',
    appId: '1:581873080046:web:2eb50842d0030478c285ff',
    messagingSenderId: '581873080046',
    projectId: 'realtimetrackerapp-53e70',
    authDomain: 'realtimetrackerapp-53e70.firebaseapp.com',
    storageBucket: 'realtimetrackerapp-53e70.firebasestorage.app',
    measurementId: 'G-GGML31EE10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO_iwJfSqjFfddpYqATMpwxZAWF6T-Zh8',
    appId: '1:581873080046:android:b9d1b3c9c292c1efc285ff',
    messagingSenderId: '581873080046',
    projectId: 'realtimetrackerapp-53e70',
    storageBucket: 'realtimetrackerapp-53e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Z6aQnwtbmwJT7Xq2nT_7ET7ymoYs8gI',
    appId: '1:581873080046:ios:c94322ae58a96854c285ff',
    messagingSenderId: '581873080046',
    projectId: 'realtimetrackerapp-53e70',
    storageBucket: 'realtimetrackerapp-53e70.firebasestorage.app',
    iosBundleId: 'com.fedaa.realtimetracker',
  );
}
